server: 
  port: 8002
---

spring:
  application:
    name: icustomer
  profiles: dev
  data:
    rest:
      base-path: api
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:customerdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
    platform: org.hibernate.dialect.H2Dialect
